export const SET_DATA = 'SET_DATA';
export const SET_ERROR = 'SET_ERROR';
export const SET_ORDER_NUMBER = 'SET_ORDER_NUMBER';
export const SET_SELECT_INGREDIENT = 'SET_SELECT_INGREDIENT';
export const DELETE_INGREDIENT_FROM_INGREDIENTS = 'DELETE_INGREDIENT_FROM_INGREDIENTS';
export const REPLACE_INNER_DRAG_INGREDIENT = 'REPLACE_INNER_DRAG_INGREDIENT';