export const OPEN_MODAL_INGREDIENT_DETAILS = 'OPEN_MODAL_INGREDIENT_DETAILS';
export const CLOSE_MODAL_INGREDIENT_DETAILS = 'CLOSE_MODAL_INGREDIENT_DETAILS';

export const OPEN_MODAL_ORDER_DETAILS = 'OPEN_MODAL_ORDER_DETAILS';
export const CLOSE_MODAL_ORDER_DETAILS = 'CLOSE_MODAL_ORDER_DETAILS';

export const SET_CURRENT_BURGER_INGREDIENTS_NAME = 'SET_CURRENT_BURGER_INGREDIENTS_NAME';